#! /bin/dash
. pigs-config

if [ ! -d "$branch/commit" ]; then
    echo "$0: error: this command can not be run until after the first commit"
    exit 1
fi

if [ "$#" -eq 0 ]; then
    for dir in .pig/branches/*; do
        echo "$dir" | sed -E 's?.pig/branches/(.*)?\1?g'
    done
elif [ "$#" -eq 1 ]; then
    if [ -e ".pig/branches/$1" ]; then
        echo "$0: error: branch '$1' already exists"
        exit 1
    fi
    mkdir ".pig/branches/$1"
    # update master
    for file in *;do
        cp "$file" "$branch/$file"
    done 
    ## for local test
    # for file in "$branch"/pigs-*; do
    #     rm "$file"
    # done

    # cope the entire master here
    cp -r .pig/branches/master/* ".pig/branches/$1/"
    rm ".pig/branches/$1/log" 2>/dev/null

elif [ "$#" -eq 2 ]; then
    if [ "$1" = '-d' ]; then 
        if [ "$2" = 'master' ]; then
            echo "$0: error: can not delete branch '$2': default branch"
            exit 1
        fi
        if [ ! -d ".pig/branches/$2" ]; then
            echo "$0: error: branch '$2' doesn't exist"
            exit 1
        fi
        rm -r ".pig/branches/$2"
        echo "Deleted branch '$2'"
    else
        echo "usage"
    fi
fi